# Generated by Django 5.0.2 on 2024-02-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_uploded_url',
            new_name='video_uploaded_url',
        ),
    ]
